version: "3.9"

services:
  app:
    # 현재 디렉토리를 빌드 컨텍스트로 사용하여 Docker 이미지를 빌드합니다.
    build:
      context: .
      # Dockerfile에 'DEV' 인자를 전달하는 데 사용
      # Dockerfile에서 빌드 과정 중에 'DEV' 변수를 true로 설정
      args:
        - DEV=true
    # 호스트의 8000번 포트를 컨테이너의 8000번 포트로 매핑합니다.
    ports:
      - "8000:8000"
    volumes:
      # 현재 디렉토리의 app 디렉토리를 컨테이너의 /app 디렉토리와 공유합니다.
      - ./app:/app
    # 컨테이너가 시작될 때 실행할 명령어를 설정합니다.
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
